タノミマスター用にSlackのガイドラインを変更
tanomimaster/community-management-resources pull request #1
Opened 2020-09-18 07:39 UTC by shintaro-minowa

2020-09-18 08:20 UTC, matsubo requested changes
一旦、slack-guidelines.mdのファイルだけのスコープでレビュー。

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> +本文書は、タノミマスターの利用者が参加するクローズドなSlackワークスペース（以下、タノミマスターワークスペース）において、参加者に期待される言動について記載したものです。
利用者だけとも限らないかなと思いました。利用者の定義によりますが。
例えば、契約主体から委託された開発ベンダーとかも参加すると思いますので。その場合、利用者とは言いづらいかなとおもいます。

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> -## ワークスペースへの加入前に確認してほしいこと
`加入の条件` か `加入方法`
とかにして、入り口を明示したいです。

現時点では、NDAを結ぶ ことかな。あと、そのための入り口はどこかを記載すべきかなと思います。
（freshdeskの問い合わせ時のカテゴリを選択させるとか。）

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> -
会社のメールアドレスにおけるドメイン単位で、ユーザ管理をデリゲーションするような運用にしたいです。

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> +    * 上述の通りタノミマスターワークスペースではオープンかつ積極的なコミュニケーションを推奨しますので、原則として、プライベートチャンネルを作成しないようにしてください
小売とメーカーのコミュニケーションチャネルとして使ってもらっても良いと思うので、制限しなくても良い気がします。

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> +タノミマスターワークスペースでは、原則としてオープンかつ積極的なコミュニケーションを推奨します。
そんなこともないような。まあ、明示するだけなら良いですけど。

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> -### カスタム絵文字の追加
削除した意図は何でしょうか？

2020-09-18 08:20 UTC, matsubo commented on slack-guidelines.md
> -本文書は、[Creative Commons — 表示 4.0 国際 — CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)の下で配布されています。当該ライセンス従う限り、自由に利用できます。
https://creativecommons.org/licenses/by/4.0/deed.ja
許諾を得ない限り、消してはいけないという理解です。

2020-09-18 08:42 UTC, shintaro-minowa commented on slack-guidelines.md
> +本文書は、タノミマスターの利用者が参加するクローズドなSlackワークスペース（以下、タノミマスターワークスペース）において、参加者に期待される言動について記載したものです。
@matsubo 
承知しました。
タノミマスターの利用者
→ タノミマスターの利用者、開発者、および運営者
でいかがでしょうか？

2020-09-18 16:39 UTC, matsubo commented
ちょっと他のドキュメントも手を入れたいです。。。

2020-10-13 05:09 UTC, shintaro-minowa commented on slack-guidelines.md
> +本文書は、タノミマスターの利用者が参加するクローズドなSlackワークスペース（以下、タノミマスターワークスペース）において、参加者に期待される言動について記載したものです。
「タノミマスターの利用者、開発者、および運営者」に変更いたしました。

2020-10-13 05:10 UTC, shintaro-minowa commented on slack-guidelines.md
> -## ワークスペースへの加入前に確認してほしいこと
freshdeskのチケット作成のURLを追加しました。
https://github.com/tanomimaster/community-management-resources/pull/1/files#diff-4d8ecbf1824bafa1b68b2490877ae4a2319747cb27ed25e0778e5620cb299d45R12

2020-10-13 05:17 UTC, shintaro-minowa commented on slack-guidelines.md
> -
下記の文章を追加しました。
https://github.com/tanomimaster/community-management-resources/pull/1/files#diff-4d8ecbf1824bafa1b68b2490877ae4a2319747cb27ed25e0778e5620cb299d45R14

2020-10-13 05:18 UTC, shintaro-minowa commented on slack-guidelines.md
> +    * 上述の通りタノミマスターワークスペースではオープンかつ積極的なコミュニケーションを推奨しますので、原則として、プライベートチャンネルを作成しないようにしてください
プライベートチャンネルに関する制限の文章を削除しました。

2020-10-13 05:19 UTC, shintaro-minowa commented on slack-guidelines.md
> -### カスタム絵文字の追加
カスタム絵文字に関する文章は不要かと思い削除いたしましたが、残しても問題なさそうであるため復活させました。

2020-10-13 05:19 UTC, shintaro-minowa commented on slack-guidelines.md
> -本文書は、[Creative Commons — 表示 4.0 国際 — CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)の下で配布されています。当該ライセンス従う限り、自由に利用できます。
削除してしまったライセンスに関する文章をもとに戻しました。

2020-11-05 09:18 UTC, matsubo approved these changes

2020-11-10 04:49 UTC, merged